title: siwapp
license: https://opensource.org/licenses/MIT

language: en
timezone: Europe/Madrid
encoding: utf-8

highlighter: pygments
kramdown:
  input: GFM

exclude:
  - .build
  - .gitignore
  - .ruby-version
  - bower.json
  - docker-compose.yml
  - package.json
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.coffee
  - README.md
  - bower_components
  - node_modules

collections:
  help:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      type: help
    values:
      layout: default
      menu_key: help
