title: siwapp
license: https://opensource.org/licenses/MIT

language: en
timezone: Europe/Madrid
encoding: utf-8

highlighter: pygments
kramdown:
    input: GFM
sass:
    style: compressed

exclude: [README.md, Gemfile, Gemfile.lock]
